version: "3.7"
volumes:
  server-node_modules:
  client-node_modules:
  data-node:

services:

  # node apps
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    container_name: prototype-client
    env_file:
      - .env
    image: prototype-client
    ports:
      - 8080:8080
    volumes:
      - ./app/client:/app/client
      - client-node_modules:/app/client/node_modules
    tty: true
    depends_on:
      - db
  
  # db
  db:
    image: mongo
    container_name: prototype_mongodb
    volumes:
        - data-node:/data/db
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  # server
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: prototype-server
    image: prototype-server
    environment:
      - NODE_ENV=development
      - COMMAND=${COMMAND:-serve}
      - PORT=8090
    env_file:
      - .env
    ports: 
      - 8090:8090
    volumes:
      - ./app/server:/app/server
      - server-node_modules:/app/server/node_modules
    tty: true
    depends_on:
      - db